name: Terraform Apply

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - uses: hashicorp/vault-action@v2
        id: vault_secrets
        with:
          url: https://vault.tenzin.io
          role: actions-runner-role-cloudflare-dns
          method: jwt
          secrets: |
            secret/data/cloudflare api_key | CLOUDFLARE_API_KEY ;
            secret/data/cloudflare email | CLOUDFLARE_EMAIL ;
     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          
      - name: Run Terraform Init
        run: terraform init
        
      - name: Run Terraform Format
        run: terraform fmt -check
        
      - name: Run Terraform Validate
        run: terraform validate -no-color

      - name: Run Terraform Apply
        env:
          CLOUDFLARE_API_KEY: ${{ steps.vault_secrets.outputs.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ steps.vault_secrets.outputs.CLOUDFLARE_EMAIL }}
        run: terraform apply -no-color -auto-approve
